services:
  resource-service:
    build:
      context: ./resource-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: ${RESOURCE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${RESOURCE_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RESOURCE_DB_PASSWORD}
      SONG_SERVICE_BASE_URL: ${SONG_SERVICE_URL}
    depends_on:
      resource-db:
        condition: service_healthy

  song-service:
    build:
      context: ./song-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: ${SONG_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${SONG_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SONG_DB_PASSWORD}
    depends_on:
      song-db:
        condition: service_healthy

  resource-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: resource-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-U", "postgres", "-d", "resource-db"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  song-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: song-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-U", "postgres", "-d", "song-db"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s