spring.application.name=api-gateway-service

server.port=8085

spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=false

spring.cloud.gateway.server.webmvc.routes[0].id=resource-service-route
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://resource-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/resources/**

spring.cloud.gateway.server.webmvc.routes[1].id=song-service-route
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://song-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/songs/**


eureka.client.service-url.defaultZone=${EUREKA_DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
# Frequency of heartbeats sent by the client to the server
eureka.instance.lease-renewal-interval-in-seconds=5
# Frequency of registry data retrieval from the server to the client's local cache
eureka.client.registry-fetch-interval-seconds=5
